/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifndef __MDM_PARAMS_H__
#define __MDM_PARAMS_H__

/*!\file mdm_params.h 
 * \brief Automatically generated header file mdm_params.h
 */


/** maximum length of a param name, not including NULL */
#define MAX_ACTUAL_MDM_PARAM_NAME_LENGTH 46

/** maximum actual instance depth */
#define MAX_ACTUAL_MDM_INSTANCE_DEPTH    4


#endif /* __MDM_PARAMS_H__ */
