gram.o: gram.c config.h includes.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/string.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/../lib/gcc/mips-linux-uclibc/4.4.2/include-fixed/features.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_config.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_arch_features.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/cdefs.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/../lib/gcc/mips-linux-uclibc/4.4.2/include/stddef.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/stdio.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/types.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/wordsize.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/kernel_types.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/typesizes.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/pthreadtypes.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sched.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_stdio.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/wchar.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/wchar.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_mutex.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/pthread.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sched.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/time.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/time.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_clk_tck.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/signal.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sigset.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/initspin.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sigthread.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_pthread.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/../lib/gcc/mips-linux-uclibc/4.4.2/include/stdarg.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/stdio_lim.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/stdlib.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/types.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/endian.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/endian.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/select.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/select.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/sysmacros.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/alloca.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/syslog.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/syslog.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/unistd.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/posix_opt.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/confname.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/getopt.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/errno.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/errno.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/errno_values.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/signum.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/siginfo.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sigaction.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sigcontext.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sgidefs.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sigstack.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/netdb.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/netinet/in.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/stdint.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/socket.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/uio.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uio.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/socket.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/../lib/gcc/mips-linux-uclibc/4.4.2/include-fixed/limits.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/../lib/gcc/mips-linux-uclibc/4.4.2/include-fixed/syslimits.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/limits.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/posix1_lim.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/local_lim.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/linux/limits.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/uClibc_local_lim.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/posix2_lim.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/sockaddr.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/asm/socket.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/asm/sockios.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/asm/ioctl.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/in.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/byteswap.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/rpc/netdb.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/netdb.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/pwd.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/grp.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/inttypes.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/param.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/linux/param.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/asm/param.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/time.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/ioctl.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/ioctls.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/asm/ioctls.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/ioctl-types.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/ttydefaults.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/stat.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/stat.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/fcntl.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/bits/fcntl.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/netinet/ip6.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/netinet/icmp6.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/arpa/inet.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/sys/sysctl.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/linux/sysctl.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/linux/kernel.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/linux/types.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/net/if.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/net/if_arp.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/getopt.h \
 radvd.h defaults.h log.h \
 /opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include/linux/version.h
