/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 31
#define BCM_REL_RELEASE 122
#define BCM_REL_PATCH 11
#define BCM_SW_VERSIONCODE (31*65536+122*256+11)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#define BCM_REL_VERSION2 31
#define BCM_REL_RELEASE2 121
#define BCM_REL_PATCH2 11
#define BCM_SW_VERSIONCODE2 (31*65536+121*256+11)
#define BCM_SW_VERSION2(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
